[package]
name = "rps-studio"
version = "0.1.0"
edition = "2021"

[dependencies]
app_dirs2 = "2.5.5"
ash = "0.38.0"
eyre = "0.6.12"
thiserror = "2.0.3"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
winit = "0.30.5"
